version: '3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cronnit
    container_name: connit
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html

  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_DATABASE: "${CRONNIT_DBNAME}"
      MYSQL_ROOT_PASSWORD: "${CRONNIT_DBPASS}"
      TZ: Europe/Berlin
    volumes:
      - ./mariadb:/var/lib/mysql
